name: "CI: Main workflow"
on: push
jobs:
  my-job:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - name: Install dependencies 
      run: npm install
    - name: Run lint
      run: npm run lint --fix
    - name: Run test
      run: npm run test